[server]
# Maximum size, in megabytes, for files uploaded with the file_uploader
maxUploadSize = 10

[theme]
# Optional: Configure theme colors (you can customize these as needed)
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
